export const environment = {
  production: true,
  apiUrl: 'NG_APP_API_URL_PLACEHOLDER',
  firebase: {
    projectId: 'NG_APP_FIREBASE_PROJECT_ID_PLACEHOLDER',
    appId: 'NG_APP_FIREBASE_APP_ID_PLACEHOLDER',
    storageBucket: 'NG_APP_FIREBASE_STORAGE_BUCKET_PLACEHOLDER',
    apiKey: 'NG_APP_FIREBASE_API_KEY_PLACEHOLDER',
    authDomain: 'NG_APP_FIREBASE_AUTH_DOMAIN_PLACEHOLDER',
    messagingSenderId: 'NG_APP_FIREBASE_MESSAGING_SENDER_ID_PLACEHOLDER'
  }
};
